# Generated by Django 6.1.1 on 2026-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='متن کامل خبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='متن کامل خبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ja',
            field=models.TextField(null=True, verbose_name='متن کامل خبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه خبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه خبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه خبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان خبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان خبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان خبر'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='عنوان دسته'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='عنوان دسته'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ja',
            field=models.CharField(max_length=150, null=True, verbose_name='عنوان دسته'),
        ),
    ]
