# Generated by Django 4.2.27 on 2025-12-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutus_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'عضو تیم', 'verbose_name_plural': 'اعضای تیم'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='about_us/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='درباره ما', max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team_members/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='لینکدین'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=255, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='توییتر'),
        ),
    ]
