# Generated by Django 4.2.27 on 2025-12-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapanChamberDirectorsMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('role', models.CharField(max_length=255, verbose_name='نقش')),
                ('image', models.ImageField(upload_to='team_members/', verbose_name='تصویر')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فیسبوک')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'هیات مدیره اتاق ژاپن',
                'verbose_name_plural': 'هیات مدیره اتاق ژاپن',
            },
        ),
    ]
