# Generated by Django 4.2.27 on 2026-01-01 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_japanchamberdirectorsmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'کشور ها',
                'verbose_name_plural': 'کشور ها',
            },
        ),
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section_type', models.CharField(choices=[('about', 'درباره کشور'), ('links', 'لینک\u200cهای ضروری'), ('reports', 'گزارش\u200cها')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.country')),
            ],
            options={
                'verbose_name': 'راهنمای تجارت',
                'verbose_name_plural': 'راهنمای تجارت ها',
            },
        ),
    ]
