# Generated by Django 4.2.27 on 2026-01-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_country_guidesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'کشور', 'verbose_name_plural': 'کشورها'},
        ),
        migrations.AlterModelOptions(
            name='guidesection',
            options={'ordering': ['order'], 'verbose_name': 'بخش راهنمای تجاری', 'verbose_name_plural': 'بخش\u200cهای راهنمای تجاری'},
        ),
        migrations.RemoveField(
            model_name='guidesection',
            name='section_type',
        ),
        migrations.AddField(
            model_name='guidesection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال باشد'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کشور'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='guidesection',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.country', verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='guidesection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='guidesection',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='guidesection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال باشد'),
        ),
        migrations.AlterField(
            model_name='guidesection',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک مرتبط (در صورت وجود)'),
        ),
        migrations.AlterField(
            model_name='guidesection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان بخش'),
        ),
    ]
