# Generated by Django 4.2.27 on 2026-01-01 11:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_country_options_alter_guidesection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidesection',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات'),
        ),
    ]
