# Generated by Django 4.2.27 on 2026-01-01 12:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_guidesection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات')),
                ('role_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='شرایط عضویت ')),
                ('link_file', models.URLField(blank=True, null=True, verbose_name='لینک مرتبط (در صورت وجود)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'خدمات اتاق مشترک و عضویت',
                'verbose_name_plural': ' خدمات اتاق مشترک و عضویت ها',
            },
        ),
    ]
