# Generated by Django 4.2.27 on 2026-06-09 11:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_memberaboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن'),
        ),
    ]
