# Generated by Django 4.2.27 on 2026-06-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_aboutus_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک'),
        ),
    ]
