# Generated by Django 4.2.27 on 2026-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(verbose_name='تاریخ ایجاد'),
        ),
    ]
