# Generated by Django 4.2.27 on 2026-09-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_slider_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام\u200cخانوادگی')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('membership_code', models.CharField(max_length=50, unique=True, verbose_name='کد عضویت')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='سمت')),
                ('photo', models.ImageField(upload_to='chamber_members/photos/', verbose_name='تصویر فرد')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='chamber_members/logos/', verbose_name='لوگوی شرکت')),
                ('bio', models.TextField(blank=True, verbose_name='توضیحات / بیوگرافی')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('website', models.URLField(blank=True, verbose_name='وبسایت شرکت')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='آدرس')),
                ('catalog', models.FileField(blank=True, null=True, upload_to='chamber_members/catalogs/', verbose_name='کاتالوگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamber_members', to='core.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'عضو اتاق بازرگانی',
                'verbose_name_plural': 'اعضای اتاق بازرگانی',
                'ordering': ['full_name'],
            },
        ),
    ]
