# Generated by Django 6.1.1 on 2026-09-06 16:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chambermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_ja',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(default='درباره ما', max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_fa',
            field=models.CharField(default='درباره ما', max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ja',
            field=models.CharField(default='درباره ما', max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='address_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='address_fa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='address_ja',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات / بیوگرافی'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='bio_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات / بیوگرافی'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='bio_ja',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات / بیوگرافی'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='company_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='company_name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='company_name_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نام و نام\u200cخانوادگی'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='full_name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نام و نام\u200cخانوادگی'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='full_name_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='نام و نام\u200cخانوادگی'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='position_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='position_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='chambermember',
            name='position_ja',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کشور'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کشور'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کشور'),
        ),
        migrations.AddField(
            model_name='guidesection',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='guidesection',
            name='description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='guidesection',
            name='description_ja',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='guidesection',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان بخش'),
        ),
        migrations.AddField(
            model_name='guidesection',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان بخش'),
        ),
        migrations.AddField(
            model_name='guidesection',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان بخش'),
        ),
        migrations.AddField(
            model_name='japanchamberdirectorsmember',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='japanchamberdirectorsmember',
            name='name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='japanchamberdirectorsmember',
            name='name_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='japanchamberdirectorsmember',
            name='role_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نقش'),
        ),
        migrations.AddField(
            model_name='japanchamberdirectorsmember',
            name='role_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نقش'),
        ),
        migrations.AddField(
            model_name='japanchamberdirectorsmember',
            name='role_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='نقش'),
        ),
        migrations.AddField(
            model_name='memberaboutsection',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='memberaboutsection',
            name='description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='memberaboutsection',
            name='description_ja',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='memberaboutsection',
            name='role_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='شرایط عضویت '),
        ),
        migrations.AddField(
            model_name='memberaboutsection',
            name='role_description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='شرایط عضویت '),
        ),
        migrations.AddField(
            model_name='memberaboutsection',
            name='role_description_ja',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='شرایط عضویت '),
        ),
        migrations.AddField(
            model_name='memberaboutsection',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان '),
        ),
        migrations.AddField(
            model_name='memberaboutsection',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان '),
        ),
        migrations.AddField(
            model_name='memberaboutsection',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان '),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نقش'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='نقش'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='نقش'),
        ),
    ]
