# Generated by Django 4.2.27 on 2025-12-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_article_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='article',
            name='whats_up',
            field=models.URLField(blank=True, null=True, verbose_name='لینک واتساپ'),
        ),
    ]
