# Generated by Django 6.1.1 on 2026-09-06 16:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='محتوا'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='محتوا'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ja',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='محتوا'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ja',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='عنوان تگ'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='عنوان تگ'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ja',
            field=models.CharField(max_length=50, null=True, verbose_name='عنوان تگ'),
        ),
    ]
