# Generated by Django 4.2.27 on 2025-12-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo/', verbose_name='لوگو')),
                ('footer_text', models.TextField(blank=True, verbose_name='متن فوتر')),
                ('whats_app', models.URLField(blank=True, verbose_name='لینک واتس اپ')),
                ('twitter', models.URLField(blank=True, verbose_name='لینک توییتر')),
                ('instagram', models.URLField(blank=True, verbose_name='لینک اینستاگرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینک لینکدین')),
                ('useful_links', models.TextField(verbose_name='لینک\u200cهای مفید (هر لینک در یک خط)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
