# Generated by Django 4.2.27 on 2025-12-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='useful_links',
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان لینک')),
                ('url', models.URLField(verbose_name='آدرس لینک')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useful_links', to='settings.sitesettings')),
            ],
            options={
                'verbose_name': 'لینک مفید',
                'verbose_name_plural': 'لینک\u200cهای مفید',
            },
        ),
    ]
