# Generated by Django 4.2.27 on 2025-12-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_sitesettings_useful_links_usefullink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='addr',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='شماره تماس'),
        ),
    ]
