# Generated by Django 4.2.27 on 2025-12-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_sitesettings_addr_sitesettings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, verbose_name='متن درباره اتاق صفحه اول'),
        ),
    ]
