# Generated by Django 4.2.27 on 2025-12-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_sitesettings_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_img',
            field=models.ImageField(blank=True, null=True, upload_to='site_about/', verbose_name='تصویر درباره اتاق'),
        ),
    ]
