# Generated by Django 4.2.27 on 2025-12-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_sitesettings_about_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='ایمیل'),
        ),
    ]
