# Generated by Django 6.1.1 on 2026-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='متن درباره اتاق صفحه اول'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_fa',
            field=models.TextField(blank=True, null=True, verbose_name='متن درباره اتاق صفحه اول'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ja',
            field=models.TextField(blank=True, null=True, verbose_name='متن درباره اتاق صفحه اول'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='addr_en',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='addr_fa',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='addr_ja',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='متن فوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_fa',
            field=models.TextField(blank=True, null=True, verbose_name='متن فوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_ja',
            field=models.TextField(blank=True, null=True, verbose_name='متن فوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='نام سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='نام سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='نام سایت'),
        ),
        migrations.AddField(
            model_name='usefullink',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان لینک'),
        ),
        migrations.AddField(
            model_name='usefullink',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان لینک'),
        ),
        migrations.AddField(
            model_name='usefullink',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان لینک'),
        ),
    ]
